### ISSUE TITLE
Test Case 6c (TC 6c): Incremental Fwd Renaming

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#15]
Suggested precondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

Set birthdays of all persons in the person register (this must be propagated as a target delta so the tools' inner state is consistent).

-------------

Then propagate the source delta renaming the larger Simpson family to Bouvier (Marge's maiden surname): 

Expected postcondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Bouvier
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Bouvier, Homer (male)
 - Bouvier, Marge (female)
 - Bouvier, Bart (male)
 - Bouvier, Bart (male)
 - Bouvier, Lisa (female)
 - Bouvier, Maggie (female)

}

**Comment by anthonyanjorin** [comment]
Features: [**fwd** | **attribute** | **fixed** | **structural** | **corr-based**]

**Comment by tbuchmann** [comment]
I added two new methods in the BXTool Interface:
- performSourceEdit
- performTargetEdit

They were required in order to get the incremental forward behavior for all TC6a-TC6e right.
If performAndPropagateTargetEdit is used instead, this creates a round-trip scenario in which e.g. medini failes on most preconditions, because the backward transformation destroys the family model.
