### ISSUE TITLE
Test Case 6d (TC 6d): Incremental Fwd Moving

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#16]
Suggested precondition:

**FamilyRegister** {
 - Skinner
 - Flanders
   - Rod (son)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Marge (mother)
    - Bart (son)
    - Bart (son)
    - Lisa (daughter)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Simpson, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Simpson, Lisa (female)
 - Simpson, Maggie (female)

}

Set birthdays of all persons in the person register (this must be propagated as a target delta so the tools' inner state is consistent).

-------------

Then propagate the source delta moving Lisa (daughter) to Flanders as Lisa (mother), and Marge (mother) to Skinner as Marge (mother): 

Expected postcondition:

**FamilyRegister** {
 - Skinner
   - Marge (mother)
 - Flanders
   - Rod (son)
   - Lisa (mother)
 - Simpson
    - Bart (father)
 - Simpson
    - Homer (father)
    - Bart (son)
    - Bart (son)
    - Maggie (daughter)

}

**PersonRegister** {
 - Flanders, Rod (male)
 - Simpson, Bart (male)
 - Simpson, Homer (male)
 - Skinner, Marge (female)
 - Simpson, Bart (male)
 - Simpson, Bart (male)
 - Flanders, Lisa (female)
 - Simpson, Maggie (female)

}

**Comment by anthonyanjorin** [comment]
Features:  [**fwd** | **del+add** | **fixed** | **structural**]

I would argue that this test is not **corr-based** as only people with unique names are relocated.

**Comment by tbuchmann** [comment]
I think "moving" refers to what can be done in e.g. the generated tree editor. In the generated editor for the Family Model, i could for example drag & drop a Family Member (Father) into an empty family. In that case i did not delete an recreate the Family Member object, i just moved it into a different container. However, since the model does neither use an unique ID attribute on Family Members nor an xmi ID attribute, it is impossible even for corr-based tools like ours to refer to the right Family Member object after the move operation.

**Comment by anthonyanjorin** [comment]
Ok, so it's structural then (you have to inspect the delta to decide correctly what happened).  I'll update the features.

**Comment by tbuchmann** [comment]
I added two new methods in the BXTool Interface:
- performSourceEdit
- performTargetEdit

They were required in order to get the incremental forward behavior for all TC6a-TC6e right.
If performAndPropagateTargetEdit is used instead, this creates a round-trip scenario in which e.g. medini failes on most preconditions, because the backward transformation destroys the family model.
