### ISSUE TITLE
Test Case 8b (TC 8b): Incremental Bwd Operational

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/benchmarx#20]
Suggested precondition:

**FamilyRegister** {
 
 - Simpson
    - Maggie (daughter)

}

**PersonRegister** {

 - Simpson, Maggie (female)

}

To finalise the precondition, set birthdays of all persons in the person register as an idle target delta.

----------------------------

Then with [e ^ p] propagate the following target edit adding:

Simpson, Marge (female)
Simpson, Lisa (female)

(respecting the _order_ of updates, Marge should be added as a mother in the existing Simpson family, Lisa as a daughter)

Then with [!e ^ p] propagate the following target edit adding:

Simpson, Lisa (female)
Simpson, Marge (female)

(respecting the _order_ of updates, a new family Simpson should be created with Lisa as mother and Marge as daughter)

Expected postcondition:

**FamilyRegister** {
 
 - Simpson
    - Maggie (daughter)
    - Marge (mother)
    - Lisa (daughter)
 - Simpson
    - Lisa (mother)
    - Marge (daughter)

}

**PersonRegister** {

 - Simpson, Maggie (female)
 - Simpson, Marge (female)
 - Simpson, Lisa (female)
 - Simpson, Lisa (female)
 - Simpson, Marge (female)

}

**Comment by anthonyanjorin** [comment]
Features:  [**bwd** | **runtime** | **operational** | **add**]

**Comment by tbuchmann** [comment]
I think there is also a slight error in the description of the test case concerning the last step:

"Then with [!e ^ p] propagate the following target edit adding:

Simpson, Lisa (female)
Simpson, Marge (female)

(respecting the order of updates, a new family Simpson should be created with Lisa as mother and Marge as daughter)"

If we propagate these 2 persons with [!e ^ p], we obtain 2 new Simpson Families, one with mother Lisa and one with mother marge, since "Prefer existing families" is set to false. However, propagating only one person with [!e ^p] and then setting [e ^p] for the second edit also doesn't help, since it is non-deterministic, which existing family is chosen for the propagation of the second person.

I'd suggest to either change the postcondition accordingly (3 Simpson families), or to skip this Test Case for the TTC version.

**Comment by anthonyanjorin** [comment]
Hmm....  I was trying to be too clever I guess :(  I propose we just remove the second propagation with [!e ^ p].  The first propagation already tests what we want to test.

**Comment by tbuchmann** [comment]
Ok.
